name: Deploy to AWS EC2
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using remote ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/production/commerce-app
            git pull origin main
            docker stop appContainer
            docker rm appContainer
            docker build -t g4-api:latest .
            docker run -d -p 80:80 -e SERVERPORT=${{ secrets.SERVERPORT}} -e SECRET=${{ secrets.SECRET}} -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} --name appContainer g4-api:latest
